version: "3"
services:
  app:
    container_name: app
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8552:8000"
    depends_on:
      - db

  db:
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "redit_db"
    volumes:
      - redit_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redit_volume:
